# Generated by Django 5.2.6 on 2025-09-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
