# Generated by Django 5.2.6 on 2025-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threads/'),
        ),
    ]
