# Generated by Django 4.2.24 on 2025-09-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_threadlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='threads_extra', to='forum.category'),
        ),
    ]
