# Generated by Django 4.2.24 on 2025-09-29 13:49

from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_thread_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=forum.models.thread_image_upload)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.thread')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
