# Generated by Django 4.2.24 on 2025-09-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_threadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='categories',
        ),
    ]
