# Generated by Django 4.2.24 on 2025-09-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_thread_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='categories',
            new_name='extra_categories',
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forum.category'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thread_images/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
